wednesday-solutions/go-template

.github/workflows/go-template-ci.yml
.pre-commit-config.yaml

move go-lint to parellel job

---

cmd/server/main.go

checkErr with zerolog

---

.pre-commit-config.yaml
daos/users.go
graphql_models/generated.go
graphql_models/generated_models.go
pkg/utl/convert/convert.go
resolver/user_mutations.resolvers.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers.go
resolver/user_queries.resolvers_test.go
schema/user.graphql

add pagination to users query

---

.github/workflows/go-template-ci.yml
.gitignore
cmd/server/main.go
daos/roles_test.go
daos/users_test.go
internal/config/config.go
internal/config/config_test.go
internal/middleware/auth/auth_test.go
pkg/utl/result_wrapper/error_test.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/subscriptions.resolvers_test.go
resolver/user_mutations.resolvers.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers_test.go
test.sh

using ./test.sh in the ci

---

.github/workflows/go-template-ci.yml

run codecov on master

---

.github/workflows/go-template-ci.yml
.gitignore
README.MD
daos/roles_test.go
daos/users_test.go
internal/config/config_test.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/subscriptions.resolvers_test.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers_test.go
test.sh
testutls/main.go

add tests for usersdao

---

cmd/server/main.go
cmd/server/main_test.go
go.mod
go.sum
test.sh

adding tests for cmd/server/main.go

---

internal/config/config_test.go
internal/middleware/auth/auth_test.go

added tests for config

---

internal/jwt/jwt_test.go

added tests for jwt

---

internal/config/config_test.go
internal/middleware/auth/auth_test.go
internal/server/server.go
internal/server/server_test.go
testutls/main.go
testutls/request.go

added tests for internal/server

---

cmd/server/main.go
cmd/server/main_test.go
internal/middleware/auth/auth_test.go
internal/service/auth_test.go
pkg/api/api.go
pkg/api/api_test.go
testutls/main.go
testutls/request.go

added tests for api

---

pkg/utl/convert/convert_test.go

add tests for convert.go

---

pkg/utl/rate_throttle/throttler.go
pkg/utl/rate_throttle/throttler_test.go
testutls/main.go

add tests for throttler.go

---

go.mod
go.sum
pkg/utl/redis_cache/redis_test.go

add tests for redis_cache/redis

---

pkg/utl/redis_cache/redis_test.go

add more tests for redis_cache/redis

---

pkg/utl/redis_cache/service_test.go

add more tests for redis_cache/service

---

resolver/role_mutations.resolvers_test.go

add tests for resolver

---

internal/middleware/auth/auth.go
pkg/api/api.go
pkg/api/api_test.go
pkg/utl/result_wrapper/error.go
resolver/subscriptions.resolvers.go

add support for subscriptions

---

testutls/main.go

fix jwt config tests

---

pkg/utl/convert/convert.go
pkg/utl/convert/convert_test.go
resolver/user_mutations.resolvers.go
resolver/user_queries.resolvers.go
resolver/user_queries.resolvers_test.go
roles.go

add support  for query users.role

---

pkg/api/api.go
pkg/api/api_test.go

fix: sonarqube issues

---

resolver/auth_mutations.resolvers.go

fix: fix duplicate config error messages

---

cmd/seeder/v2/2_users.go
internal/middleware/auth/auth.go

feat: better auth whitelisting for queries, mutations and subscriptions

---

makefile
scripts/migrate-and-run.sh

feat: better makefile and clean up migrate-and-run.sh

---

daos/roles_test.go
daos/users_test.go
go.mod
go.sum
internal/jwt/jwt_test.go
internal/middleware/auth/auth_test.go
models/gorp_migrations.go
models/roles.go
models/users.go
pkg/utl/rediscache/service_test.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/subscriptions.resolvers_test.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers_test.go

feat: bump up sqlboiler

---

internal/controller/healthcheck.go
internal/server/server.go

feat: add controller folder structure

---

.gitignore
Dockerfile
cmd/seeder/exec/seed.go
cmd/seeder/v2/2_users.go
docker-compose.yml
internal/config/env.go

feat: cleanup

---

cmd/server/main_test.go
daos/users_test.go
internal/config/config_test.go
internal/jwt/jwt_test.go
internal/middleware/auth/auth_test.go
pkg/utl/rediscache/service_test.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers_test.go

fix: added fix to tests where env files were loaded

---

internal/config/env_test.go
internal/jwt/jwt_test.go
internal/server/error_test.go

Increased code coverage

---

.github/workflows/go-template-ci.yml

fix: workflow fix for fork PRs

---

.github/workflows/go-template-ci.yml
.golangci.yml
README.MD
sonar-project.properties

Docs update

---

resolver/user_mutations.resolvers_test.go

user mutaion tests refactor

---

resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/user_mutations.resolvers_test.go

refactor auth mutation resolver test

---

go.mod
go.sum
internal/server/error_test.go
internal/server/server_test.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/user_mutations.resolvers_test.go

error_test.go and server_test.go

---

cmd/server/main_test.go
daos/users_test.go
go.mod
go.sum
internal/config/config.go
internal/config/config_test.go
internal/config/env.go
internal/config/env_test.go
internal/jwt/jwt_test.go
internal/middleware/auth/auth_test.go
internal/server/error_test.go
internal/server/server_test.go
pkg/utl/rediscache/service_test.go
pkg/utl/resultwrapper/error_test.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go
resolver/user_mutations.resolvers_test.go
resolver/user_queries.resolvers_test.go
testutls/main.go

feat: neater tests

---

go.sum
internal/server/server_test.go
internal/service/auth.go
pkg/utl/secure/secure.go
resolver/auth_mutations.resolvers.go
resolver/auth_mutations.resolvers_test.go
resolver/role_mutations.resolvers_test.go

feat: neater login test

---

resolver/user_mutations.resolvers_test.go

usermutaion resolved

---

pkg/api/api_test.go

neater api test

---

.pre-commit-config.yaml

Added Pre-commit hooks in the  go- template

Feat: Add Pre-commit hooks

---

.pre-commit-config.yaml

Reverts wednesday-solutions/go-template#151
@himanshu-wedensday this breaks the CI. Reverting it

Revert "Feat: Add Pre-commit hooks"
